repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--no-error-on-unmatched-pattern]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        files: (src/htmst/.+py|tests/.+py)$
        language: system
        pass_filenames: false
